### ISSUE TITLE
REACH: Fix the ability icon starting off with darkened cooldown effect on bottom half of icon

### ISSUE THREAD

**Issue by clarkm25** [n8hopp/mageburn#51]
This does not stop the user from using the ability but could be nice to fix for quality of life. Not important though so it is definitely a reach goal

**Comment by n8hopp** [comment]
Literally just set the ProgressBar underneath K and L in the ingame_ui to have 0 fill. Super easy, literally 10 second fix

**Comment by HarryThVu** [comment]
Seems like this has been fix in main branch
