### ISSUE TITLE
BUG: Damage numbers not displaying correctly (or health not being set correctly)

### ISSUE THREAD

**Issue by clarkm25** [n8hopp/mageburn#65]
When leveling up, it shows a +1 instead of a +11

**Comment by n8hopp** [comment]
The issue with this is that the bonus is not showing properly in the GUI - the actual number that pops up is the actual number that is being added

**Comment by n8hopp** [comment]
For additional reference - the constitution bonus is -5, but it's showing as "+5" for some reason
